/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import comunes.Conexiones;

/**
 *
 * @author velasam
 */
public class PantallaJuego extends javax.swing.JFrame {
    
    Conexiones con;

    /**
     * Creates new form PantallaJuego
     *
     */
    public PantallaJuego(Conexiones con) throws InterruptedException {
        initComponents();
        monst1.setVisible(false);
        monst2.setVisible(false);
        monst3.setVisible(false);
        monst4.setVisible(false);
        monst5.setVisible(false);
        monst6.setVisible(false);
        monst7.setVisible(false);
        monst8.setVisible(false);
        monst9.setVisible(false);
        monst10.setVisible(false);
        monst11.setVisible(false);
        monst12.setVisible(false);
        finJuego.setVisible(false);
        this.con = con;
        this.username.setText(con.getUser());
    }

    public void editaVictimas(String texto) {
        victimas.setText(texto);
    }
    
    public void pintaVictoria(String nombre) {
        victoria.setVisible(true);
        victoria.setText(victoria.getText() + nombre + "!");
    }
    
    
    public void pintaMonstruo(int num, boolean pinta) {
        switch (num) {
            case 1: monst1.setVisible(pinta);
                    monst1.setEnabled(pinta);
                    break;
            case 2: monst2.setVisible(pinta);
                    monst2.setEnabled(pinta);
                    break;
            case 3: monst3.setVisible(pinta);
                    monst3.setEnabled(pinta);
                    break;
            case 4: monst4.setVisible(pinta);
                    monst4.setEnabled(pinta);
                    break;
            case 5: monst5.setVisible(pinta);
                    monst5.setEnabled(pinta);
                    break;
            case 6: monst6.setVisible(pinta);
                    monst6.setEnabled(pinta);
                    break;
            case 7: monst7.setVisible(pinta);
                    monst7.setEnabled(pinta);
                    break;
            case 8: monst8.setVisible(pinta);
                    monst8.setEnabled(pinta);
                    break;
            case 9: monst9.setVisible(pinta);
                    monst9.setEnabled(pinta);
                    break;
            case 10: monst10.setVisible(pinta);
                    monst10.setEnabled(pinta);
                    break;
            case 11: monst11.setVisible(pinta);
                    monst11.setEnabled(pinta);
                    break;
            case 12: monst12.setVisible(pinta);
                    monst12.setEnabled(pinta);
                    break;
        }
    }
    
    public void enviaGolpe() {
        try {
            KillSender ks = new KillSender(con);
            ks.start();
            ks.join();
            System.out.println("Golpe enviado.");
            editaVictimas("" + ks.getVictimas());
            String ganador = ks.getGanador();
            if (ganador != null && !ganador.equals("-")) {
                monsts.setVisible(false);
                finJuego.setVisible(true);
                pintaVictoria(ganador);
            }
        } catch (InterruptedException ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monsts = new javax.swing.JPanel();
        monst1 = new javax.swing.JLabel();
        monst5 = new javax.swing.JLabel();
        monst2 = new javax.swing.JLabel();
        monst9 = new javax.swing.JLabel();
        monst10 = new javax.swing.JLabel();
        monst6 = new javax.swing.JLabel();
        monst3 = new javax.swing.JLabel();
        monst7 = new javax.swing.JLabel();
        monst11 = new javax.swing.JLabel();
        monst8 = new javax.swing.JLabel();
        monst12 = new javax.swing.JLabel();
        monst4 = new javax.swing.JLabel();
        victimas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        finJuego = new javax.swing.JPanel();
        replay = new javax.swing.JButton();
        victoria = new javax.swing.JLabel();
        victoria1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monster Haven");
        setMinimumSize(new java.awt.Dimension(613, 368));
        setResizable(false);
        getContentPane().setLayout(null);

        monsts.setMinimumSize(new java.awt.Dimension(613, 368));
        monsts.setOpaque(false);
        monsts.setLayout(null);

        monst1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/ghostsmol.gif"))); // NOI18N
        monst1.setEnabled(false);
        monst1.setName("monst1"); // NOI18N
        monst1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monst1MouseClicked(evt);
            }
        });
        monsts.add(monst1);
        monst1.setBounds(70, 130, 110, 80);

        monst5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/blobsmol.gif"))); // NOI18N
        monst5.setEnabled(false);
        monst5.setName("monst5"); // NOI18N
        monst5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monst5MouseClicked(evt);
            }
        });
        monsts.add(monst5);
        monst5.setBounds(70, 180, 110, 80);

        monst2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/blobsmol.gif"))); // NOI18N
        monst2.setEnabled(false);
        monst2.setName("monst2"); // NOI18N
        monst2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monst2MouseClicked(evt);
            }
        });
        monsts.add(monst2);
        monst2.setBounds(190, 130, 110, 80);

        monst9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/ghostsmol.gif"))); // NOI18N
        monst9.setEnabled(false);
        monst9.setName("monst9"); // NOI18N
        monst9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monst9MouseClicked(evt);
            }
        });
        monsts.add(monst9);
        monst9.setBounds(70, 240, 110, 80);

        monst10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/blobsmol.gif"))); // NOI18N
        monst10.setEnabled(false);
        monst10.setName("monst10"); // NOI18N
        monst10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monst10MouseClicked(evt);
            }
        });
        monsts.add(monst10);
        monst10.setBounds(190, 240, 110, 80);

        monst6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/ghostsmol.gif"))); // NOI18N
        monst6.setEnabled(false);
        monst6.setName("monst6"); // NOI18N
        monst6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monst6MouseClicked(evt);
            }
        });
        monsts.add(monst6);
        monst6.setBounds(190, 180, 110, 80);

        monst3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/ghostsmol.gif"))); // NOI18N
        monst3.setEnabled(false);
        monst3.setName("monst3"); // NOI18N
        monst3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monst3MouseClicked(evt);
            }
        });
        monsts.add(monst3);
        monst3.setBounds(320, 130, 110, 80);

        monst7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/blobsmol.gif"))); // NOI18N
        monst7.setEnabled(false);
        monst7.setName("monst7"); // NOI18N
        monst7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monst7MouseClicked(evt);
            }
        });
        monsts.add(monst7);
        monst7.setBounds(320, 180, 110, 80);

        monst11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/ghostsmol.gif"))); // NOI18N
        monst11.setEnabled(false);
        monst11.setName("monst11"); // NOI18N
        monst11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monst11MouseClicked(evt);
            }
        });
        monsts.add(monst11);
        monst11.setBounds(320, 240, 110, 80);

        monst8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/ghostsmol.gif"))); // NOI18N
        monst8.setEnabled(false);
        monst8.setName("monst8"); // NOI18N
        monst8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monst8MouseClicked(evt);
            }
        });
        monsts.add(monst8);
        monst8.setBounds(430, 180, 110, 80);

        monst12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/blobsmol.gif"))); // NOI18N
        monst12.setEnabled(false);
        monst12.setName("monst12"); // NOI18N
        monst12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monst12MouseClicked(evt);
            }
        });
        monsts.add(monst12);
        monst12.setBounds(430, 240, 110, 80);

        monst4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/blobsmol.gif"))); // NOI18N
        monst4.setEnabled(false);
        monst4.setName("monst4"); // NOI18N
        monst4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monst4MouseClicked(evt);
            }
        });
        monsts.add(monst4);
        monst4.setBounds(430, 130, 110, 80);

        victimas.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        victimas.setForeground(new java.awt.Color(255, 255, 153));
        victimas.setText("0");
        victimas.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        monsts.add(victimas);
        victimas.setBounds(530, 20, 70, 18);

        jLabel2.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Monstruos:");
        monsts.add(jLabel2);
        jLabel2.setBounds(420, 20, 100, 18);

        username.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 153));
        username.setText("user");
        monsts.add(username);
        username.setBounds(20, 20, 320, 18);

        getContentPane().add(monsts);
        monsts.setBounds(0, 0, 610, 340);

        finJuego.setMinimumSize(new java.awt.Dimension(613, 368));
        finJuego.setOpaque(false);
        finJuego.setLayout(null);

        replay.setBackground(new java.awt.Color(255, 255, 153));
        replay.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        replay.setText("Jugar de nuevo");
        replay.setAlignmentY(0.0F);
        replay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 153), 1, true));
        replay.setBorderPainted(false);
        replay.setName("botonInicio"); // NOI18N
        replay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replayActionPerformed(evt);
            }
        });
        finJuego.add(replay);
        replay.setBounds(220, 180, 170, 31);

        victoria.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        victoria.setForeground(new java.awt.Color(255, 255, 153));
        victoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        victoria.setText("¡Ha ganado ");
        victoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        finJuego.add(victoria);
        victoria.setBounds(0, 70, 610, 60);

        victoria1.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        victoria1.setForeground(new java.awt.Color(255, 255, 153));
        victoria1.setText("¡Fin del juego!");
        victoria1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        finJuego.add(victoria1);
        victoria1.setBounds(190, 10, 230, 60);

        getContentPane().add(finJuego);
        finJuego.setBounds(-1, -1, 610, 340);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/imagenes/fondoBig.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monst1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monst1MouseClicked
        pintaMonstruo(1, false);
        enviaGolpe();
    }//GEN-LAST:event_monst1MouseClicked

    private void monst2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monst2MouseClicked
        pintaMonstruo(2, false);
        enviaGolpe();
    }//GEN-LAST:event_monst2MouseClicked

    private void monst3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monst3MouseClicked
        pintaMonstruo(3, false);
        enviaGolpe();
    }//GEN-LAST:event_monst3MouseClicked

    private void monst4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monst4MouseClicked
        pintaMonstruo(4, false);
        enviaGolpe();
    }//GEN-LAST:event_monst4MouseClicked

    private void monst8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monst8MouseClicked
        pintaMonstruo(8, false);
        enviaGolpe();
    }//GEN-LAST:event_monst8MouseClicked

    private void monst7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monst7MouseClicked
        pintaMonstruo(7, false);
        enviaGolpe();
    }//GEN-LAST:event_monst7MouseClicked

    private void monst6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monst6MouseClicked
        pintaMonstruo(6, false);
        enviaGolpe();
    }//GEN-LAST:event_monst6MouseClicked

    private void monst5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monst5MouseClicked
        pintaMonstruo(5, false);
        enviaGolpe();
    }//GEN-LAST:event_monst5MouseClicked

    private void monst9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monst9MouseClicked
        pintaMonstruo(9, false);
        enviaGolpe();
    }//GEN-LAST:event_monst9MouseClicked

    private void monst10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monst10MouseClicked
        pintaMonstruo(10, false);
        enviaGolpe();
    }//GEN-LAST:event_monst10MouseClicked

    private void monst11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monst11MouseClicked
        pintaMonstruo(11, false);
        enviaGolpe();
    }//GEN-LAST:event_monst11MouseClicked

    private void monst12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monst12MouseClicked
       pintaMonstruo(12, false);
        enviaGolpe();
    }//GEN-LAST:event_monst12MouseClicked

    private void replayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replayActionPerformed
        InicioJuego ini = new InicioJuego();
        ini.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_replayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel finJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel monst1;
    private javax.swing.JLabel monst10;
    private javax.swing.JLabel monst11;
    private javax.swing.JLabel monst12;
    private javax.swing.JLabel monst2;
    private javax.swing.JLabel monst3;
    private javax.swing.JLabel monst4;
    private javax.swing.JLabel monst5;
    private javax.swing.JLabel monst6;
    private javax.swing.JLabel monst7;
    private javax.swing.JLabel monst8;
    private javax.swing.JLabel monst9;
    private javax.swing.JPanel monsts;
    private javax.swing.JButton replay;
    private javax.swing.JLabel username;
    private javax.swing.JLabel victimas;
    private javax.swing.JLabel victoria;
    private javax.swing.JLabel victoria1;
    // End of variables declaration//GEN-END:variables
}
